### PR TITLE
Dynamic fields

### PR DESCRIPTION
**Pull request by jasoncoon**

### CODE REVIEW

**Comment by terrag42** [comment]
Could you elaborate on what extra functionality dynamic fields gives the software? Does it have to do with the "sparking" and "cooling" sliders for the heatMap function?

**Comment by jasoncoon** [comment]
Yeah, it allows you to define and expose adjustable variables in the firmware and have them just show up in the web UI, without having to change the web app code at all.  It's still not quite how I want it, but it's getting closer.  :)

**Comment by terrag42** [comment]
Wow, this is a great idea. So far I haven't been able to make "sparking" or "cooling" sliders show up though. The "speed" slider stays visible for all patterns. I noticed that in the Arduino IDE, the color of the word "speed" gets changed to orange, but not so for "sparking" or "cooling". Keep up the good work!

**Comment by jasoncoon-firemon** [comment]
Thanks!  Hrm, have you uploaded the new firmware to the board, and uploaded the web app to SPIFFS?  Changes were required to both to make it work.

**Comment by jasoncoon** [comment]
Thanks! Hrm, have you uploaded the new firmware to the board, and uploaded the web app to SPIFFS? Changes were required to both to make it work.

**Pull request merged**
